/**
  * 임베디드 DB 전용 스키마 생성
    * 테스트 코드 실행시 자동으로 실행됨
 */

drop table if exists item CASCADE;
create table item
(
    id        bigint generated by default as identity,
    item_name varchar(10),
    price     integer,
    quantity  integer,
    primary key (id)
);